export const THEME_TOKEN_GROUPS = [
  {
    id: 'core',
    label: 'Core Surfaces',
    tokens: [
      { key: '--vera-bg', label: 'App background', type: 'color' },
      { key: '--vera-surface', label: 'Surface', type: 'color' },
      { key: '--vera-panel', label: 'Panel', type: 'color' },
      { key: '--vera-panel-alt', label: 'Panel alt', type: 'color' },
      { key: '--vera-panel-muted', label: 'Panel muted', type: 'color' },
      { key: '--vera-text', label: 'Text primary', type: 'color' },
      { key: '--vera-text-muted', label: 'Text muted', type: 'color' },
      { key: '--vera-border', label: 'Border', type: 'color' },
      { key: '--vera-shadow', label: 'Shadow color', type: 'color' },
      { key: '--vera-icon', label: 'Icon color', type: 'color' },
    ],
  },
  {
    id: 'accent',
    label: 'Accents & Status',
    tokens: [
      { key: '--vera-accent', label: 'Accent', type: 'color' },
      { key: '--vera-accent-strong', label: 'Accent strong', type: 'color' },
      { key: '--vera-accent-soft', label: 'Accent soft', type: 'color' },
      { key: '--vera-accent-faint', label: 'Accent faint', type: 'color' },
      { key: '--vera-secondary', label: 'Secondary accent', type: 'color' },
      { key: '--vera-success', label: 'Success', type: 'color' },
      { key: '--vera-warning', label: 'Warning', type: 'color' },
      { key: '--vera-danger', label: 'Danger', type: 'color' },
      { key: '--vera-info', label: 'Info', type: 'color' },
      { key: '--primary-color-text', label: 'Accent text', type: 'color' },
    ],
  },
  {
    id: 'components',
    label: 'Component Surfaces',
    tokens: [
      { key: '--vera-header-bg', label: 'Header background', type: 'color' },
      { key: '--vera-sidebar-bg', label: 'Sidebar background', type: 'color' },
      { key: '--vera-input-bg', label: 'Input background', type: 'color' },
      { key: '--vera-input-text', label: 'Input text', type: 'color' },
      { key: '--vera-input-bar-bg', label: 'Input bar background', type: 'color' },
      { key: '--vera-input-bar-border', label: 'Input bar border', type: 'color' },
      { key: '--vera-input-bar-glow', label: 'Input bar glow', type: 'shadow' },
      { key: '--vera-tool-card-bg', label: 'Tool card background', type: 'color' },
      { key: '--vera-tool-card-border', label: 'Tool card border', type: 'color' },
      { key: '--vera-tool-card-glow', label: 'Tool card glow', type: 'shadow' },
      { key: '--vera-message-user-bg', label: 'User message background', type: 'color' },
      { key: '--vera-message-assistant-bg', label: 'Assistant message background', type: 'color' },
      { key: '--vera-message-user-border', label: 'User message border', type: 'color' },
      { key: '--vera-message-assistant-border', label: 'Assistant message border', type: 'color' },
      { key: '--vera-code-bg', label: 'Code block background', type: 'color' },
      { key: '--vera-code-border', label: 'Code block border', type: 'color' },
      { key: '--vera-scrollbar-track', label: 'Scrollbar track', type: 'color' },
      { key: '--vera-scrollbar-thumb', label: 'Scrollbar thumb', type: 'color' },
      { key: '--vera-scrollbar-thumb-hover', label: 'Scrollbar thumb hover', type: 'color' },
      { key: '--vera-scroll-btn-bg', label: 'Scroll button background', type: 'color' },
      { key: '--vera-scroll-btn-border', label: 'Scroll button border', type: 'color' },
    ],
  },
  {
    id: 'panels',
    label: 'Panels & Drawers',
    tokens: [
      { key: '--vera-drawer-bg', label: 'Drawer background', type: 'color' },
      { key: '--vera-drawer-border', label: 'Drawer border', type: 'color' },
      { key: '--vera-drawer-card-bg', label: 'Drawer card background', type: 'color' },
      { key: '--vera-code-editor-bg', label: 'Code editor background', type: 'color' },
      { key: '--vera-terminal-bg', label: 'Terminal background', type: 'color' },
      { key: '--vera-terminal-header-bg', label: 'Terminal header background', type: 'color' },
      { key: '--vera-file-browser-bg', label: 'File browser background', type: 'color' },
      { key: '--vera-dialog-content-bg', label: 'Dialog content background', type: 'color' },
      { key: '--vera-card-bg', label: 'Card background', type: 'color' },
      { key: '--vera-filter-button-bg', label: 'Filter button background', type: 'color' },
      { key: '--vera-filter-button-active-bg', label: 'Filter button active background', type: 'color' },
      { key: '--vera-nixie-button-bg', label: 'Nixie button background', type: 'color' },
    ],
  },
  {
    id: 'voice',
    label: 'Voice Controls',
    tokens: [
      { key: '--vera-voice-listening', label: 'Voice listening', type: 'color' },
      { key: '--vera-voice-listening-glow', label: 'Voice listening glow', type: 'color' },
      { key: '--vera-voice-listening-text', label: 'Voice listening text', type: 'color' },
      { key: '--vera-voice-speaking', label: 'Voice speaking', type: 'color' },
      { key: '--vera-voice-speaking-glow', label: 'Voice speaking glow', type: 'color' },
      { key: '--vera-voice-speaking-text', label: 'Voice speaking text', type: 'color' },
      { key: '--vera-voice-processing', label: 'Voice processing', type: 'color' },
      { key: '--vera-voice-processing-glow', label: 'Voice processing glow', type: 'color' },
      { key: '--vera-voice-connecting', label: 'Voice connecting', type: 'color' },
    ],
  },
  {
    id: 'effects',
    label: 'Glass & Effects',
    tokens: [
      { key: '--vera-glass-bg', label: 'Glass background', type: 'color' },
      { key: '--vera-glass-strong', label: 'Glass strong background', type: 'color' },
      { key: '--vera-glass-border', label: 'Glass border', type: 'color' },
      { key: '--vera-glow-soft', label: 'Glow soft', type: 'shadow' },
      { key: '--vera-glow-strong', label: 'Glow strong', type: 'shadow' },
      { key: '--vera-panel-shadow', label: 'Panel shadow', type: 'shadow' },
      { key: '--vera-message-shadow', label: 'Message shadow', type: 'shadow' },
      { key: '--vera-panel-edge', label: 'Panel edge', type: 'color' },
      { key: '--vera-message-edge', label: 'Message edge', type: 'color' },
      { key: '--vera-panel-inner-glow', label: 'Panel inner glow', type: 'shadow' },
      { key: '--vera-panel-bevel', label: 'Panel bevel', type: 'shadow' },
      { key: '--vera-ripple-color', label: 'Button ripple', type: 'color' },
    ],
  },
  {
    id: 'advanced',
    label: 'Advanced Tokens',
    tokens: [
      { key: '--vera-message-glow', label: 'Message glow', type: 'shadow' },
      { key: '--vera-send-button-glow', label: 'Send button glow', type: 'shadow' },
      { key: '--vera-avatar-glow', label: 'Avatar glow', type: 'shadow' },
      { key: '--vera-accent-02', label: 'Accent 2%', type: 'color' },
      { key: '--vera-accent-03', label: 'Accent 3%', type: 'color' },
      { key: '--vera-accent-04', label: 'Accent 4%', type: 'color' },
      { key: '--vera-accent-06', label: 'Accent 6%', type: 'color' },
      { key: '--vera-accent-18', label: 'Accent 18%', type: 'color' },
      { key: '--vera-accent-45', label: 'Accent 45%', type: 'color' },
      { key: '--vera-accent-85', label: 'Accent 85%', type: 'color' },
      { key: '--vera-secondary-02', label: 'Secondary 2%', type: 'color' },
      { key: '--vera-secondary-35', label: 'Secondary 35%', type: 'color' },
      { key: '--vera-secondary-80', label: 'Secondary 80%', type: 'color' },
      { key: '--vera-success-60', label: 'Success 60%', type: 'color' },
      { key: '--vera-warning-60', label: 'Warning 60%', type: 'color' },
      { key: '--vera-error-60', label: 'Error 60%', type: 'color' },
      { key: '--vera-info-60', label: 'Info 60%', type: 'color' },
      { key: '--vera-black-60', label: 'Black 60%', type: 'color' },
      { key: '--vera-black-70', label: 'Black 70%', type: 'color' },
      { key: '--vera-black-80', label: 'Black 80%', type: 'color' },
      { key: '--vera-black-90', label: 'Black 90%', type: 'color' },
      { key: '--vera-black-95', label: 'Black 95%', type: 'color' },
      { key: '--vera-white-03', label: 'White 3%', type: 'color' },
      { key: '--vera-white-30', label: 'White 30%', type: 'color' },
      { key: '--vera-white-60', label: 'White 60%', type: 'color' },
      { key: '--vera-white-95', label: 'White 95%', type: 'color' },
      { key: '--vera-white-98', label: 'White 98%', type: 'color' },
      { key: '--consume-duration', label: 'Swarm consume duration', type: 'time' },
      { key: '--glow-strength', label: 'Vera glow strength', type: 'number' },
      { key: '--indicator-size', label: 'Swarm indicator size', type: 'length' },
      { key: '--line-delay', label: 'Swarm line delay', type: 'time' },
      { key: '--logo-height', label: 'Vera logo height', type: 'length' },
      { key: '--logo-width', label: 'Vera logo width', type: 'length' },
      { key: '--orbit-delay', label: 'Swarm orbit delay', type: 'time' },
      { key: '--orbit-duration', label: 'Swarm orbit duration', type: 'time' },
      { key: '--orbit-radius', label: 'Swarm orbit radius', type: 'length' },
      { key: '--orbit-rotation', label: 'Swarm orbit rotation', type: 'number' },
      { key: '--orbit-size', label: 'Swarm orbit size', type: 'length' },
      { key: '--orbit-tilt', label: 'Swarm orbit tilt', type: 'number' },
      { key: '--split-offset', label: 'Vera split offset', type: 'length' },
      { key: '--stream-opacity', label: 'Vera stream opacity', type: 'number' },
      { key: '--wing-token-rate', label: 'Wing token rate', type: 'number' },
    ],
  },
];

export const THEME_TOKEN_INDEX = THEME_TOKEN_GROUPS.reduce((acc, group) => {
  group.tokens.forEach((token) => {
    acc[token.key] = token;
  });
  return acc;
}, {});
